#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPExifData.h"
#import "ASPTiffFrame.h"


@protocol ASPTiffProperties
@end

@interface ASPTiffProperties : ASPObject


@property(nonatomic) NSArray<ASPTiffFrame>* frames;

@property(nonatomic) NSString* byteOrder;

@property(nonatomic) ASPExifData* exifData;

@end
