#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol ASPTiffOptions
@end

@interface ASPTiffOptions : ASPObject


@property(nonatomic) NSNumber* isValid;

@property(nonatomic) NSString* artist;

@property(nonatomic) NSString* byteOrder;

@property(nonatomic) NSArray* /* NSNumber */ bitsPerSample;

@property(nonatomic) NSString* compression;

@property(nonatomic) NSString* copyright;

@property(nonatomic) NSArray* /* NSNumber */ colorMap;

@property(nonatomic) NSString* dateTime;

@property(nonatomic) NSString* documentName;

@property(nonatomic) NSString* alphaStorage;

@property(nonatomic) NSString* fillOrder;

@property(nonatomic) NSArray* /* NSNumber */ halfToneHints;

@property(nonatomic) NSString* imageDescription;

@property(nonatomic) NSString* inkNames;

@property(nonatomic) NSString* scannerManufacturer;

@property(nonatomic) NSArray* /* NSNumber */ maxSampleValue;

@property(nonatomic) NSArray* /* NSNumber */ minSampleValue;

@property(nonatomic) NSString* scannerModel;

@property(nonatomic) NSString* pageName;

@property(nonatomic) NSString* orientation;

@property(nonatomic) NSArray* /* NSNumber */ pageNumber;

@property(nonatomic) NSString* photometric;

@property(nonatomic) NSString* planarConfiguration;

@property(nonatomic) NSString* resolutionUnit;

@property(nonatomic) NSNumber* rowsPerStrip;

@property(nonatomic) NSArray* /* NSString */ sampleFormat;

@property(nonatomic) NSNumber* samplesPerPixel;

@property(nonatomic) NSArray* /* NSNumber */ smaxSampleValue;

@property(nonatomic) NSArray* /* NSNumber */ sminSampleValue;

@property(nonatomic) NSString* softwareType;

@property(nonatomic) NSArray* /* NSNumber */ stripByteCounts;

@property(nonatomic) NSArray* /* NSNumber */ stripOffsets;

@property(nonatomic) NSString* subFileType;

@property(nonatomic) NSString* targetPrinter;

@property(nonatomic) NSString* threshholding;

@property(nonatomic) NSNumber* totalPages;

@property(nonatomic) NSNumber* xposition;

@property(nonatomic) NSNumber* xresolution;

@property(nonatomic) NSNumber* yposition;

@property(nonatomic) NSNumber* yresolution;

@property(nonatomic) NSString* faxT4Options;

@property(nonatomic) NSString* predictor;

@property(nonatomic) NSNumber* imageLength;

@property(nonatomic) NSNumber* imageWidth;

@property(nonatomic) NSNumber* validTagCount;

@property(nonatomic) NSNumber* bitsPerPixel;

@end
