<?php
namespace Aspose\Imaging\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class ExifData {
	static $swaggerTypes = array(
		'ApertureValue' => 'float',
		'BodySerialNumber' => 'string',
		'BrightnessValue' => 'float',
		'CFAPattern' => 'string',
		'CameraOwnerName' => 'string',
		'ColorSpace' => 'string',
		'ComponentsConfiguration' => 'string',
		'CompressedBitsPerPixel' => 'float',
		'Contrast' => 'string',
		'CustomRendered' => 'string',
		'DateTimeDigitized' => 'string',
		'DateTimeOriginal' => 'string',
		'DeviceSettingDescription' => 'string',
		'DigitalZoomRatio' => 'float',
		'ExifVersion' => 'string',
		'ExposureBiasValue' => 'float',
		'ExposureIndex' => 'float',
		'ExposureMode' => 'string',
		'ExposureProgram' => 'string',
		'ExposureTime' => 'float',
		'FNumber' => 'float',
		'FileSource' => 'string',
		'Flash' => 'string',
		'FlashEnergy' => 'float',
		'FlashpixVersion' => 'string',
		'FocalLength' => 'float',
		'FocalLengthIn35MmFilm' => 'integer',
		'FocalPlaneResolutionUnit' => 'string',
		'FocalPlaneXResolution' => 'float',
		'FocalPlaneYResolution' => 'float',
		'GPSAltitude' => 'float',
		'GPSAltitudeRef' => 'string',
		'GPSAreaInformation' => 'string',
		'GPSDOP' => 'float',
		'GPSDestBearing' => 'float',
		'GPSDestBearingRef' => 'string',
		'GPSDestDistance' => 'float',
		'GPSDestDistanceRef' => 'string',
		'GPSDestLatitude' => 'array[float]',
		'GPSDestLatitudeRef' => 'string',
		'GPSDestLongitude' => 'array[float]',
		'GPSDestLongitudeRef' => 'string',
		'GPSDifferential' => 'integer',
		'GPSImgDirection' => 'float',
		'GPSImgDirectionRef' => 'string',
		'GPSDateStamp' => 'string',
		'GPSLatitude' => 'array[float]',
		'GPSLatitudeRef' => 'string',
		'GPSLongitude' => 'array[float]',
		'GPSLongitudeRef' => 'string',
		'GPSMapDatum' => 'string',
		'GPSMeasureMode' => 'string',
		'GPSProcessingMethod' => 'string',
		'GPSSatellites' => 'string',
		'GPSSpeed' => 'float',
		'GPSSpeedRef' => 'string',
		'GPSStatus' => 'string',
		'GPSTimestamp' => 'array[float]',
		'GPSTrack' => 'string',
		'GPSTrackRef' => 'string',
		'GPSVersionID' => 'string',
		'GainControl' => 'string',
		'Gamma' => 'float',
		'ISOSpeed' => 'integer',
		'ISOSpeedLatitudeYYY' => 'integer',
		'ISOSpeedLatitudeZZZ' => 'integer',
		'PhotographicSensitivity' => 'integer',
		'ImageUniqueID' => 'string',
		'LensMake' => 'string',
		'LensModel' => 'string',
		'LensSerialNumber' => 'string',
		'LensSpecification' => 'array[float]',
		'LightSource' => 'string',
		'MakerNoteRawData' => 'string',
		'MaxApertureValue' => 'float',
		'MeteringMode' => 'string',
		'OECF' => 'string',
		'PixelXDimension' => 'integer',
		'PixelYDimension' => 'integer',
		'RecommendedExposureIndex' => 'integer',
		'RelatedSoundFile' => 'string',
		'Saturation' => 'string',
		'SceneCaptureType' => 'string',
		'SceneType' => 'integer',
		'SensingMethod' => 'string',
		'SensitivityType' => 'integer',
		'Sharpness' => 'integer',
		'ShutterSpeedValue' => 'float',
		'SpatialFrequencyResponse' => 'string',
		'SpectralSensitivity' => 'string',
		'StandardOutputSensitivity' => 'integer',
		'SubjectArea' => 'array[integer]',
		'SubjectDistance' => 'float',
		'SubjectDistanceRange' => 'string',
		'SubjectLocation' => 'array[integer]',
		'SubsecTime' => 'string',
		'SubsecTimeDigitized' => 'string',
		'SubsecTimeOriginal' => 'string',
		'UserComment' => 'string',
		'WhiteBalance' => 'string',
		'WhitePoint' => 'array[float]'

	);

	public $ApertureValue; // float
	public $BodySerialNumber; // string
	public $BrightnessValue; // float
	public $CFAPattern; // string
	public $CameraOwnerName; // string
	public $ColorSpace; // string
	public $ComponentsConfiguration; // string
	public $CompressedBitsPerPixel; // float
	public $Contrast; // string
	public $CustomRendered; // string
	public $DateTimeDigitized; // string
	public $DateTimeOriginal; // string
	public $DeviceSettingDescription; // string
	public $DigitalZoomRatio; // float
	public $ExifVersion; // string
	public $ExposureBiasValue; // float
	public $ExposureIndex; // float
	public $ExposureMode; // string
	public $ExposureProgram; // string
	public $ExposureTime; // float
	public $FNumber; // float
	public $FileSource; // string
	public $Flash; // string
	public $FlashEnergy; // float
	public $FlashpixVersion; // string
	public $FocalLength; // float
	public $FocalLengthIn35MmFilm; // integer
	public $FocalPlaneResolutionUnit; // string
	public $FocalPlaneXResolution; // float
	public $FocalPlaneYResolution; // float
	public $GPSAltitude; // float
	public $GPSAltitudeRef; // string
	public $GPSAreaInformation; // string
	public $GPSDOP; // float
	public $GPSDestBearing; // float
	public $GPSDestBearingRef; // string
	public $GPSDestDistance; // float
	public $GPSDestDistanceRef; // string
	public $GPSDestLatitude; // array[float]
	public $GPSDestLatitudeRef; // string
	public $GPSDestLongitude; // array[float]
	public $GPSDestLongitudeRef; // string
	public $GPSDifferential; // integer
	public $GPSImgDirection; // float
	public $GPSImgDirectionRef; // string
	public $GPSDateStamp; // string
	public $GPSLatitude; // array[float]
	public $GPSLatitudeRef; // string
	public $GPSLongitude; // array[float]
	public $GPSLongitudeRef; // string
	public $GPSMapDatum; // string
	public $GPSMeasureMode; // string
	public $GPSProcessingMethod; // string
	public $GPSSatellites; // string
	public $GPSSpeed; // float
	public $GPSSpeedRef; // string
	public $GPSStatus; // string
	public $GPSTimestamp; // array[float]
	public $GPSTrack; // string
	public $GPSTrackRef; // string
	public $GPSVersionID; // string
	public $GainControl; // string
	public $Gamma; // float
	public $ISOSpeed; // integer
	public $ISOSpeedLatitudeYYY; // integer
	public $ISOSpeedLatitudeZZZ; // integer
	public $PhotographicSensitivity; // integer
	public $ImageUniqueID; // string
	public $LensMake; // string
	public $LensModel; // string
	public $LensSerialNumber; // string
	public $LensSpecification; // array[float]
	public $LightSource; // string
	public $MakerNoteRawData; // string
	public $MaxApertureValue; // float
	public $MeteringMode; // string
	public $OECF; // string
	public $PixelXDimension; // integer
	public $PixelYDimension; // integer
	public $RecommendedExposureIndex; // integer
	public $RelatedSoundFile; // string
	public $Saturation; // string
	public $SceneCaptureType; // string
	public $SceneType; // integer
	public $SensingMethod; // string
	public $SensitivityType; // integer
	public $Sharpness; // integer
	public $ShutterSpeedValue; // float
	public $SpatialFrequencyResponse; // string
	public $SpectralSensitivity; // string
	public $StandardOutputSensitivity; // integer
	public $SubjectArea; // array[integer]
	public $SubjectDistance; // float
	public $SubjectDistanceRange; // string
	public $SubjectLocation; // array[integer]
	public $SubsecTime; // string
	public $SubsecTimeDigitized; // string
	public $SubsecTimeOriginal; // string
	public $UserComment; // string
	public $WhiteBalance; // string
	public $WhitePoint; // array[float]
	}

