<?php
namespace Aspose\Imaging\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class GifProperties {
	static $swaggerTypes = array(
		'BackgroundColor' => 'string',
		'HasTrailer' => 'bool',
		'PixelAspectRatio' => 'integer'

	);

	public $BackgroundColor; // string
	public $HasTrailer; // bool
	public $PixelAspectRatio; // integer
	}

