<?php
namespace Aspose\Imaging\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class JfifData {
	static $swaggerTypes = array(
		'DensityUnits' => 'string',
		'Version' => 'integer',
		'XDensity' => 'integer',
		'YDensity' => 'integer'

	);

	public $DensityUnits; // string
	public $Version; // integer
	public $XDensity; // integer
	public $YDensity; // integer
	}

