<?php
namespace Aspose\Imaging\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class JpegProperties {
	static $swaggerTypes = array(
		'Comment' => 'string',
		'JpegExifData' => 'JpegExifData',
		'JpegJfifData' => 'JfifData'

	);

	public $Comment; // string
	public $JpegExifData; // JpegExifData
	public $JpegJfifData; // JfifData
	}

