<?php
namespace Aspose\Imaging\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class PsdProperties {
	static $swaggerTypes = array(
		'BitsPerChannel' => 'int',
		'ChannelsCount' => 'int',
		'ColorMode' => 'string',
		'Compression' => 'string'

	);

	public $BitsPerChannel; // int
	public $ChannelsCount; // int
	public $ColorMode; // string
	public $Compression; // string
	}

