<?php
namespace Aspose\Imaging\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class BmpProperties {
	static $swaggerTypes = array(
		'Compression' => 'string'

	);

	public $Compression; // string
	}

