<?php
namespace Aspose\Imaging\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class ImagingResponse {
	static $swaggerTypes = array(
		'Height' => 'int',
		'Width' => 'int',
		'BitsPerPixel' => 'int',
		'BmpProperties' => 'BmpProperties',
		'GifProperties' => 'GifProperties',
		'JpegProperties' => 'JpegProperties',
		'PngProperties' => 'PngProperties',
		'TiffProperties' => 'TiffProperties',
		'PsdProperties' => 'PsdProperties',
		'HorizontalResolution' => 'float',
		'VerticalResolution' => 'float',
		'IsCached' => 'bool',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $Height; // int
	public $Width; // int
	public $BitsPerPixel; // int
	public $BmpProperties; // BmpProperties
	public $GifProperties; // GifProperties
	public $JpegProperties; // JpegProperties
	public $PngProperties; // PngProperties
	public $TiffProperties; // TiffProperties
	public $PsdProperties; // PsdProperties
	public $HorizontalResolution; // float
	public $VerticalResolution; // float
	public $IsCached; // bool
	public $Code; // string
	public $Status; // string
	}

