<?php
namespace Aspose\Imaging\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class TiffProperties {
	static $swaggerTypes = array(
		'ByteOrder' => 'string',
		'ExifData' => 'ExifData'

	);

	public $ByteOrder; // string
	public $ExifData; // ExifData
	}

