#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol ASPGifProperties
@end

@interface ASPGifProperties : ASPObject


@property(nonatomic) NSString* backgroundColor;

@property(nonatomic) NSNumber* hasTrailer;

@property(nonatomic) NSString* pixelAspectRatio;

@end
