#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol ASPJpegExifData
@end

@interface ASPJpegExifData : ASPObject


@property(nonatomic) NSString* artist;

@property(nonatomic) NSString* copyright;

@property(nonatomic) NSString* dateTime;

@property(nonatomic) NSString* imageDescription;

@property(nonatomic) NSString* make;

@property(nonatomic) NSString* model;

@property(nonatomic) NSString* orientation;

@property(nonatomic) NSArray* /* NSNumber */ primaryChromaticities;

@property(nonatomic) NSArray* /* NSNumber */ referenceBlackWhite;

@property(nonatomic) NSString* resolutionUnit;

@property(nonatomic) NSString* software;

@property(nonatomic) NSArray* /* NSNumber */ transferFunction;

@property(nonatomic) NSNumber* xResolution;

@property(nonatomic) NSArray* /* NSNumber */ yCbCrCoefficients;

@property(nonatomic) NSString* yCbCrPositioning;

@property(nonatomic) NSNumber* yResolution;

@property(nonatomic) NSNumber* apertureValue;

@property(nonatomic) NSString* bodySerialNumber;

@property(nonatomic) NSNumber* brightnessValue;

@property(nonatomic) NSString* cFAPattern;

@property(nonatomic) NSString* cameraOwnerName;

@property(nonatomic) NSString* colorSpace;

@property(nonatomic) NSString* componentsConfiguration;

@property(nonatomic) NSNumber* compressedBitsPerPixel;

@property(nonatomic) NSString* contrast;

@property(nonatomic) NSString* customRendered;

@property(nonatomic) NSString* dateTimeDigitized;

@property(nonatomic) NSString* dateTimeOriginal;

@property(nonatomic) NSString* deviceSettingDescription;

@property(nonatomic) NSNumber* digitalZoomRatio;

@property(nonatomic) NSString* exifVersion;

@property(nonatomic) NSNumber* exposureBiasValue;

@property(nonatomic) NSNumber* exposureIndex;

@property(nonatomic) NSString* exposureMode;

@property(nonatomic) NSString* exposureProgram;

@property(nonatomic) NSNumber* exposureTime;

@property(nonatomic) NSNumber* fNumber;

@property(nonatomic) NSString* fileSource;

@property(nonatomic) NSString* flash;

@property(nonatomic) NSNumber* flashEnergy;

@property(nonatomic) NSString* flashpixVersion;

@property(nonatomic) NSNumber* focalLength;

@property(nonatomic) NSNumber* focalLengthIn35MmFilm;

@property(nonatomic) NSString* focalPlaneResolutionUnit;

@property(nonatomic) NSNumber* focalPlaneXResolution;

@property(nonatomic) NSNumber* focalPlaneYResolution;

@property(nonatomic) NSNumber* gPSAltitude;

@property(nonatomic) NSString* gPSAltitudeRef;

@property(nonatomic) NSString* gPSAreaInformation;

@property(nonatomic) NSNumber* gPSDOP;

@property(nonatomic) NSNumber* gPSDestBearing;

@property(nonatomic) NSString* gPSDestBearingRef;

@property(nonatomic) NSNumber* gPSDestDistance;

@property(nonatomic) NSString* gPSDestDistanceRef;

@property(nonatomic) NSArray* /* NSNumber */ gPSDestLatitude;

@property(nonatomic) NSString* gPSDestLatitudeRef;

@property(nonatomic) NSArray* /* NSNumber */ gPSDestLongitude;

@property(nonatomic) NSString* gPSDestLongitudeRef;

@property(nonatomic) NSNumber* gPSDifferential;

@property(nonatomic) NSNumber* gPSImgDirection;

@property(nonatomic) NSString* gPSImgDirectionRef;

@property(nonatomic) NSString* gPSDateStamp;

@property(nonatomic) NSArray* /* NSNumber */ gPSLatitude;

@property(nonatomic) NSString* gPSLatitudeRef;

@property(nonatomic) NSArray* /* NSNumber */ gPSLongitude;

@property(nonatomic) NSString* gPSLongitudeRef;

@property(nonatomic) NSString* gPSMapDatum;

@property(nonatomic) NSString* gPSMeasureMode;

@property(nonatomic) NSString* gPSProcessingMethod;

@property(nonatomic) NSString* gPSSatellites;

@property(nonatomic) NSNumber* gPSSpeed;

@property(nonatomic) NSString* gPSSpeedRef;

@property(nonatomic) NSString* gPSStatus;

@property(nonatomic) NSArray* /* NSNumber */ gPSTimestamp;

@property(nonatomic) NSString* gPSTrack;

@property(nonatomic) NSString* gPSTrackRef;

@property(nonatomic) NSString* gPSVersionID;

@property(nonatomic) NSString* gainControl;

@property(nonatomic) NSNumber* gamma;

@property(nonatomic) NSNumber* iSOSpeed;

@property(nonatomic) NSNumber* iSOSpeedLatitudeYYY;

@property(nonatomic) NSNumber* iSOSpeedLatitudeZZZ;

@property(nonatomic) NSNumber* photographicSensitivity;

@property(nonatomic) NSString* imageUniqueID;

@property(nonatomic) NSString* lensMake;

@property(nonatomic) NSString* lensModel;

@property(nonatomic) NSString* lensSerialNumber;

@property(nonatomic) NSArray* /* NSNumber */ lensSpecification;

@property(nonatomic) NSString* lightSource;

@property(nonatomic) NSString* makerNoteRawData;

@property(nonatomic) NSNumber* maxApertureValue;

@property(nonatomic) NSString* meteringMode;

@property(nonatomic) NSString* oECF;

@property(nonatomic) NSNumber* pixelXDimension;

@property(nonatomic) NSNumber* pixelYDimension;

@property(nonatomic) NSNumber* recommendedExposureIndex;

@property(nonatomic) NSString* relatedSoundFile;

@property(nonatomic) NSString* saturation;

@property(nonatomic) NSString* sceneCaptureType;

@property(nonatomic) NSString* sceneType;

@property(nonatomic) NSString* sensingMethod;

@property(nonatomic) NSNumber* sensitivityType;

@property(nonatomic) NSNumber* sharpness;

@property(nonatomic) NSNumber* shutterSpeedValue;

@property(nonatomic) NSString* spatialFrequencyResponse;

@property(nonatomic) NSString* spectralSensitivity;

@property(nonatomic) NSNumber* standardOutputSensitivity;

@property(nonatomic) NSArray* /* NSNumber */ subjectArea;

@property(nonatomic) NSNumber* subjectDistance;

@property(nonatomic) NSString* subjectDistanceRange;

@property(nonatomic) NSArray* /* NSNumber */ subjectLocation;

@property(nonatomic) NSString* subsecTime;

@property(nonatomic) NSString* subsecTimeDigitized;

@property(nonatomic) NSString* subsecTimeOriginal;

@property(nonatomic) NSString* userComment;

@property(nonatomic) NSString* whiteBalance;

@property(nonatomic) NSArray* /* NSNumber */ whitePoint;

@end
