#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol ASPJfifData
@end

@interface ASPJfifData : ASPObject


@property(nonatomic) NSString* densityUnits;

@property(nonatomic) NSNumber* version;

@property(nonatomic) NSNumber* xDensity;

@property(nonatomic) NSNumber* yDensity;

@end
