#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPExifData.h"
#import "ASPTiffOptions.h"


@protocol ASPTiffFrame
@end

@interface ASPTiffFrame : ASPObject


@property(nonatomic) ASPTiffOptions* frameOptions;

@property(nonatomic) NSNumber* height;

@property(nonatomic) NSNumber* width;

@property(nonatomic) ASPExifData* exifData;

@end
